/// Flutter icons DuckDuckGo
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DuckDuckGo
///      fonts:
///       - asset: fonts/DuckDuckGo.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
///
import 'package:flutter/widgets.dart';

class DuckDuckGo {
  DuckDuckGo._();

  static const _kFontFam = 'DuckDuckGo';
  static const String? _kFontPkg = null;

  static const IconData duckduckgo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
